# Generated by Django 5.0.6 on 2024-05-12 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cause',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Повод',
                'verbose_name_plural': 'Поводы',
            },
        ),
        migrations.CreateModel(
            name='Collect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('cause', models.CharField(max_length=40, verbose_name='Повод')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('close_date', models.DateTimeField(blank=True, default=None, verbose_name='Дата завершения')),
                ('max_amount', models.PositiveIntegerField(blank=True, default=0, verbose_name='Максимальная сумма')),
                ('image', models.ImageField(upload_to='collects/images/', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Денежный сбор',
                'verbose_name_plural': 'Денежные сборы',
            },
        ),
    ]
