# Generated by Django 5.0.6 on 2024-05-13 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collects', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collect',
            name='close_date',
            field=models.DateTimeField(blank=True, verbose_name='Дата завершения'),
        ),
    ]
