# Generated by Django 5.0.6 on 2024-05-12 11:09

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('collects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.BooleanField(default=False, verbose_name='Ежемесячное пожертвование')),
                ('invest_amount', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(50)], verbose_name='Сумма пожертвования')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('comment', models.TextField(verbose_name='Комментарий')),
                ('public', models.BooleanField(default=True, verbose_name='Сумма публична')),
                ('collect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='collects.collect', verbose_name='Денежный сбор')),
            ],
        ),
    ]
