# Generated by Django 5.0.6 on 2024-05-09 14:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collects', '0001_initial'),
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='organization',
        ),
        migrations.AddField(
            model_name='payment',
            name='collect',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='collects.collect', verbose_name='Денежный сбор'),
            preserve_default=False,
        ),
    ]
